<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-28T11:29:34 EDT" name="Default suite" finished-at="2024-05-28T11:29:40 EDT" duration-ms="6216">
    <groups>
    </groups>
    <test started-at="2024-05-28T11:29:34 EDT" name="Default test" finished-at="2024-05-28T11:29:40 EDT" duration-ms="6216">
      <class name="com.Itlearn.testcases.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.Itlearn.testcases.LoginTest@407cf41]" started-at="2024-05-28T11:29:34 EDT" name="setup" finished-at="2024-05-28T11:29:37 EDT" duration-ms="2633" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoging(java.lang.String,java.lang.String)[pri:0, instance:com.Itlearn.testcases.LoginTest@407cf41]" started-at="2024-05-28T11:29:37 EDT" name="verifyLoging" data-provider="loginData" finished-at="2024-05-28T11:29:39 EDT" duration-ms="2118" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Demo12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123456$]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoging -->
        <test-method signature="verifyLoging(java.lang.String,java.lang.String)[pri:0, instance:com.Itlearn.testcases.LoginTest@407cf41]" started-at="2024-05-28T11:29:39 EDT" name="verifyLoging" data-provider="loginData" finished-at="2024-05-28T11:29:40 EDT" duration-ms="1108" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[SONA]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[T12345]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.Itlearn.testcases.LoginTest.verifyLoging(LoginTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoging -->
      </class> <!-- com.Itlearn.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
